name: lc-monkey

services:
  lm-pg:
    image: postgres:17.2
    container_name: lm-pg
    restart: no
    healthcheck:
      test: "psql -U root lm_database -c ''"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      POSTGRES_MULTIPLE_DATABASES: lm_database
    volumes:
      - lm-pg-data:/var/lib/postgresql
      - ./postgres:/docker-entrypoint-initdb.d

  lm-redis:
    image: redis:7.4.2-alpine
    container_name: lm-redis
    restart: no
    ports:
      - '6379:6379'

  lm-bullboard:
    image: venatum/bull-board:2.2
    container_name: lm-bullboard
    restart: no
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: lm-redis
      REDIS_PORT: 6379
    depends_on:
      - lm-redis

volumes:
  lm-pg-data:
